name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */8 * * *'

jobs:
  backup:
    name: バックアップ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: バックアップの初期化
        run: find . -type d -mindepth 1 -maxdepth 1 -iname '*.git' -and -not -iname '.git' | parallel -v rm -rf

      - name: リポジトリの取得
        run: curl https://api.github.com/users/azisaba/repos | jq -r '.[].clone_url' > repo.txt

      - name: バックアップの作成
        run: parallel -a repo.txt git clone --bare

      - uses: stefanzweifel/git-auto-commit-action@v4
